"""Added event outcome

Revision ID: 8ed310dc933a
Revises: ee83a090158b
Create Date: 2025-10-04 19:29:17.116282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed310dc933a'
down_revision: Union[str, Sequence[str], None] = 'ee83a090158b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('happenings', sa.Column('event_outcome', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('happenings', 'event_outcome')
    # ### end Alembic commands ###
